const express = require('express')
const router = express.Router()
const { addAddress, getAddress, deleteAddress, updateUser, uploadUserImage, getUser, getUserById, getAllArtist, getAllUser, getAllArtistExceptLogger, upgradeRoleRequest, getUpgradeRoleReq, upgradeRoleResponse, deleteUpgradeRoleNotif } = require('../controller/userController')
const { protect } = require('../middleware/authMiddleware')
const upload = require('../middleware/multerConfig')

router.route('/').get(protect, getUser)
router.route('/admin').get(protect, getAllUser)
router.route('/artist').get(protect, getAllArtist)
router.route('/collab').get(protect, getAllArtistExceptLogger)
router.route('/profile').patch(protect, updateUser)
router.route('/upload').post(protect, upload.single('img'), uploadUserImage)
router.route('/address').post(protect, addAddress).get(protect, getAddress)
router.route('/upgrade/request').post(protect, upgradeRoleRequest).get(getUpgradeRoleReq)
router.route('/upgrade/response').patch(protect, upgradeRoleResponse)
router.route('/upgrade/reject/:id').delete(deleteUpgradeRoleNotif)
router.route('/:id').get(protect, getUserById)
router.route('/address/:id').delete(protect, deleteAddress)

module.exports = router